# Generated by Django 2.2.4 on 2021-11-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('dosis', models.CharField(max_length=500)),
            ],
        ),
    ]
